### ISSUE TITLE
Improve default email template / css

### ISSUE THREAD

**Issue by pcreux** [BrewhouseTeam/brewhouse-rails-template#26]
@patdryburgh @lmnelson 

What should we use for emails css? http://foundation.zurb.com/emails/email-templates.html

**Comment by lmnelson** [comment]
Chuck mentioned the other day that it sucked. It also adds a bunch of
unnecessary bloat that we don't need. I think they are based of of "Ink"
which is Zurbs email framework. But basically it has a bunch of components
that are already in Bootstrap. My suggestion would be to use Roadie. Mark
and Chuck may have more insight into this though.

**Comment by pcreux** [comment]
Hey Lee,

This sounds good to me. So we would just use plain html/css for emails unless we need a complex template.

To make it clear: Roadie is a tool that inlines css styles, it does not provide any styles.

@chuckbergeron Any take on this? Any boilerplate you use for emails?

**Comment by chuckbergeron** [comment]
This is what I've been using lately @lmnelson @pcreux -- https://www.sendwithus.com/resources/templates

I've been stripping their templates down and rebuilding them as simple as possible with the content we need (for Vey, Avenue, etc)

**Comment by pcreux** [comment]
Sounds like a plan. :rainbow:
